const { JWT_SIGNATURE, TOKEN_EXPIRY, HTTPS, PORT, G_SUITE_DOMAIN,
  GOOGLE_SSO_URL, GOOGLE_ENTITY_ID, GOOGLE_CERT_NAME, AZURE_IDENTITY_METADATA,
  AZURE_CLIENT_ID, AZURE_COOKIE_KEY, AZURE_COOKIE_IV, AZURE_CLIENT_SECRET,
  GSUITE_CLIENT_ID, GSUITE_CLIENT_SECRET, GSUITE_API_KEY,
  JUMPCLOUD_CERT_NAME } = process.env;

module.exports = {
  JWT_SIGNATURE,
  TOKEN_EXPIRY,
  HTTPS, PORT,
  G_SUITE_DOMAIN,
  GOOGLE_SSO_URL,
  GOOGLE_ENTITY_ID,
  GOOGLE_CERT_NAME,
  AZURE_IDENTITY_METADATA,
  AZURE_CLIENT_ID,
  AZURE_COOKIE_KEY,
  AZURE_COOKIE_IV,
  AZURE_CLIENT_SECRET,
  GSUITE_CLIENT_ID,
  GSUITE_CLIENT_SECRET,
  GSUITE_API_KEY,
  JUMPCLOUD_CERT_NAME
}